// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_dotwidget.cpp"
#include "EWIEGA46WW/moc_gameboardwidget.cpp"
#include "EWIEGA46WW/moc_gamescreenwidget.cpp"
#include "EWIEGA46WW/moc_mainmenuwidget.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
